//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaleLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class sale
    {
        public string id { get; set; }
        public string product_code { get; set; }
        public int quantity { get; set; }
        public System.DateTime saleDate { get; set; }
    
        public virtual employee employee { get; set; }
        public virtual product product { get; set; }
    }
}
